// <auto-generated />
namespace WebApplicationLogin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_quizs_conn_to_question : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_quizs_conn_to_question));
        
        string IMigrationMetadata.Id
        {
            get { return "201701232150343_Add_quizs_conn_to_question"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
