// <auto-generated />
namespace WebApplicationLogin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_plan_Modif_SClass_Subject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_plan_Modif_SClass_Subject));
        
        string IMigrationMetadata.Id
        {
            get { return "201701231433197_Add_plan_Modif_SClass_Subject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
