//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationLogin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplicationLogin.Resources.HomeLang", typeof(HomeLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powtórz hasło.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-Dziennik.
        /// </summary>
        public static string e_Dziennik {
            get {
                return ResourceManager.GetString("e_Dziennik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eDziennik.
        /// </summary>
        public static string eDziennik {
            get {
                return ResourceManager.GetString("eDziennik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapomniałeś hasła?.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internetowy dziennik.
        /// </summary>
        public static string Internetowydziennik {
            get {
                return ResourceManager.GetString("Internetowydziennik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Język.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nauczyciel.
        /// </summary>
        public static string Nauczyciel {
            get {
                return ResourceManager.GetString("Nauczyciel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj mnie jako nowego użytkownika.
        /// </summary>
        public static string Registerasanewuser {
            get {
                return ResourceManager.GetString("Registerasanewuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamiętaj mnie.
        /// </summary>
        public static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzic.
        /// </summary>
        public static string Rodzic {
            get {
                return ResourceManager.GetString("Rodzic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekcja dla nauczycieli.
        /// </summary>
        public static string Sekcjadlanauczycieli {
            get {
                return ResourceManager.GetString("Sekcjadlanauczycieli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekcja dla rodziców.
        /// </summary>
        public static string Sekcjadlarodziców {
            get {
                return ResourceManager.GetString("Sekcjadlarodziców", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekcja dla uczniów.
        /// </summary>
        public static string Sekcjadlauczniów {
            get {
                return ResourceManager.GetString("Sekcjadlauczniów", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uczeń.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj.
        /// </summary>
        public static string Zaloguj {
            get {
                return ResourceManager.GetString("Zaloguj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobacz.
        /// </summary>
        public static string Zobacz {
            get {
                return ResourceManager.GetString("Zobacz", resourceCulture);
            }
        }
    }
}
